### ISSUE TITLE
Bug: query arguments are added as a tag even when `WithOmitArgs()` is set

### ISSUE THREAD

**Issue by aaslamin** [luna-duclos/instrumentedsql#10]
#### Expected

When the `WithOmitArgs()` is set, I expect query arguments to not be included in any of the spans.

#### Current behaviour

The arg tag is correctly omitted from the `sql-conn-exec` span, but it is included in the `sql-stmt-exec`. This may be specifically related to named queries?

![image](https://user-images.githubusercontent.com/1800781/47238350-bd57c080-d396-11e8-977f-2ea4f6b840fa.png)

_Cc: @luna-duclos_

**Comment by luna-duclos** [comment]
I can see the issue, we are explicitly setting args in some places while we should leave it up to logQuery to do it.

**Comment by aaslamin** [comment]
> I've got a fix up in #11, could you check if it fixes your problem ?

🚤 Thanks! Looking now. Will need to fork this temporarily to test your fix.
