### ISSUE TITLE
When the wrapping driver returns ErrSkip, queries are double-logged

### ISSUE THREAD

**Issue by LeSam** [luna-duclos/instrumentedsql#17]
https://github.com/luna-duclos/instrumentedsql/blob/master/sql.go#L310

If the wrapped driver implements neither Queryer nor QueryerContext, we log the query twice, once in QueryerContext and once when the statement is prepared and executed after ErrSkip. I propose it would be better to check earlier whether the driver implements these interfaces (we can cache the check if performance is a worry) and if not, immediately return ErrSkip from QueryerContext without extra logging (to better reflect the behavior of the unwrapped driver).

I am willing to work on a patch if this change sounds ok.

**Comment by luna-duclos** [comment]
This sounds perfectly reasonable, would gladly accept a PR

**Comment by luna-duclos** [comment]
Will be fixed when #25 gets merged

**Comment by DejeroDaniel** [comment]
Unfortunately still getting this issue on 1.1.0 . I am currently using the go-mysql driver and sqlx, not sure if that is related. I don't get this problem with the original  ExpansiveWorlds/instrumentedsql wrapper.

**Comment by luna-duclos** [comment]
Alright, will have another look at this sometime this week! Thanks for the report :)
