### ISSUE TITLE
cloud.google.com/go/trace no longer exists

### ISSUE THREAD

**Issue by zikaeroh** [luna-duclos/instrumentedsql#29]
```
	github.com/luna-duclos/instrumentedsql tested by
	github.com/luna-duclos/instrumentedsql.test imports
	github.com/luna-duclos/instrumentedsql/google imports
	cloud.google.com/go/trace: module cloud.google.com/go@latest (v0.46.2) found, but does not contain package cloud.google.com/go/trace
```

This package had been marked obsolete and has now been removed in the latest release, so this repo no longer builds if 0.46.2 is used.

https://github.com/googleapis/google-cloud-go/commit/dc456904c5ef3d6d21c01ce09dfce15891aa3cea

**Comment by JonLundy** [comment]
@luna-duclos @slomek Can you push a new version tag so `go mod` will see this change?

**Comment by luna-duclos** [comment]
Tag has been created, can you confirm all works for you now ?

**Comment by JonLundy** [comment]
@luna-duclos seems to be good to me
