### ISSUE TITLE
Too many dependencies because of sql_example_test.go

### ISSUE THREAD

**Issue by dolmen** [luna-duclos/instrumentedsql#30]
[`sql_example_test.go`](/luna-duclos/instrumentedsql/blob/master/sql_example_test.go#L8) brings [many many many dependencies](/luna-duclos/instrumentedsql/blob/master/go.sum), just for testing.
This pollutes the `go.sum` of this package and the `go.sum` of downstream projects as well (even if using instrumentedsql just in tests) and makes hard for those projects to keep track of dependency to decide upgrades.

Please consider moving this test to a separate _module_ to reduce `go.sum` pollution.

**Comment by luna-duclos** [comment]
I was under the impression that go was smart enough to only populate actually required dependencies in downstream projects rather than every test dependency as well, is this incorrect ?

**Comment by slomek** [comment]
I believe my PR fixes this (https://github.com/luna-duclos/instrumentedsql/pull/33)

**Comment by luna-duclos** [comment]
Indeed it does, closing

**Comment by dolmen** [comment]
Sorry, but no, this issue is not fixed when working with Go modules.

Here is the current list of dependencies in go.mod:
```
	cloud.google.com/go v0.45.1
	cloud.google.com/go/pubsub v1.0.1 // indirect
	github.com/DATA-DOG/go-sqlmock v1.3.3 // indirect
	github.com/aws/aws-sdk-go v1.23.19 // indirect
	github.com/aws/aws-xray-sdk-go v0.9.4
	github.com/cihub/seelog v0.0.0-20170130134532-f561c5e57575 // indirect
	github.com/go-sql-driver/mysql v1.4.1
	github.com/mattn/go-sqlite3 v1.11.0
	github.com/opentracing/opentracing-go v1.1.0
	github.com/pkg/errors v0.8.1 // indirect
	github.com/stretchr/testify v1.4.0 // indirect
	go.opencensus.io v0.22.1
```
Many direct dependencies should be removed.

**Comment by dolmen** [comment]
The real fix is to create separate Go modules for google/opentracing/opencensus/xray.
I would like to make a PR for that, but I can't because the fix requires a multiple steps process that involves intermediate pushes to the main repo.

@luna-duclos Here is the step-by-step process:
```
( cd google ; go mod init ; go mod tidy )
( cd opentracing ; go mod init ; go mod tidy )
( cd opencensus ; go mod init ; go mod tidy )
( cd xray ; go mod init ; go mod tidy )
go mod tidy
git add go.sum */go.mod */go.sum
git commit -m "Separate modules for implementation specific tracers"
V=$(TZ=UTC git log -1 '--date=format-local:%Y%m%d%H%M%S' --abbrev=12 '--pretty=tformat:v0.0.0-%cd-%h')
git push
( cd google ; go get github.com/luna-duclos/instrumentedsql@$V ; go mod tidy )
( cd opentracing ; go get github.com/luna-duclos/instrumentedsql@$V ; go mod tidy )
( cd opencencus ; go get github.com/luna-duclos/instrumentedsql@$V ; go mod tidy )
( cd xray ; go get github.com/luna-duclos/instrumentedsql@$V ; go mod tidy )
git add */go.mod */go.sum
git commit -m "Fix dependencies for implementation specific tracers"
```

**Comment by luna-duclos** [comment]
Thanks for the exhaustive steps! Will look into it soon

**Comment by dolmen** [comment]
@luna-duclos ping

**Comment by luna-duclos** [comment]
At long last, this should be properly fixed, it took a few extra steps, but nothing major.
@dolmen can you confirm v1.1.3 looks good ?

**Comment by dolmen** [comment]
🎉 🍾   🎉🍾  🎉🍾  🎉🍾  🎉🍾  🎉🍾  🎉🍾  🎉🍾  🎉 
I'm so grateful for this fix!!!!!!

And I'm sorry to not have noticed it before.
