### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by aaslamin** [luna-duclos/instrumentedsql#6]
Hi @luna-duclos,

Thank you for forking this and adding the features you have added!

I was wondering if you are still maintaining this project as I am planning on using it in another (big) project?

_Cc: @aeneasr_

**Comment by aaslamin** [comment]
Great, thanks for the update @luna-duclos 👌 

Do you think we can start tagging releases as it makes it easier for someone using a dependency manager (e.g. dep and modules) to maintain their respective project(s). Right now everything is going straight into master so people would have to lock down on a commit and be extra careful upgrading by examining diffs between commits.

**Comment by luna-duclos** [comment]
Tagging releases would be good, I'll try and have a look at that when I have some time.

**Comment by aaslamin** [comment]
Awesome @luna-duclos, feel free to close this issue if you want.

**Comment by luna-duclos** [comment]
Gonna leave this issue open to keep track of tagging

**Comment by luna-duclos** [comment]
A `v1` tag has been created
