### ISSUE TITLE
Adhere to opentracing semantics when tagging a span as "error"

### ISSUE THREAD

**Issue by aaslamin** [luna-duclos/instrumentedsql#7]
#### Expected behaviour
When tagging a span as error, the [opentracing specification states](https://opentracing.io/specification/conventions/) that one should add a tag named `error`. 

#### Current behaviour
This package is adding a tag named `err` which does not get rendered appropriately by a tracing system that is OT compliant - see screenshot from Jaeger:

![image](https://user-images.githubusercontent.com/1800781/47036655-c136d900-d131-11e8-869c-8019013e158a.png)

#### Proposal

Update https://github.com/luna-duclos/instrumentedsql/blob/master/opentracing/tracer.go#L52 such that it sets a tag named `error` instead.

---

✋@luna-duclos I am happy to raise PR if you agree with the above

**Comment by luna-duclos** [comment]
Absolutely agree, I was not aware of this. To not cause unexpected behaviour for other tracers, lets only change opentracing ?

**Comment by aaslamin** [comment]
That sounds good to me @luna-duclos, I will make the change ASAP.
